#! /bin/sh

####            STARTUP         ####

pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --restore &

####            MONITOR         ####

bspc monitor -d I II III IV V VI VII VIII IX X


####            CONFIG          ####

bspc config border_width                2
bspc config window_gap                  6
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config normal_border_color         "#44475a"
bspc config active_border_color         "#bd93f9"
bspc config focused_border_color        "#ff79c6"
bspc config presel_feedback_color       "#6272a4"
bspc config focus_follows_pointer       true
bspc config top_padding                 20
bspc config bottom_padding              20

bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config pointer_action2             resize_corner

####            RULES           ####

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a SimpleScreenRecorder state=floating
bspc rula -a discord desktop'^3'
bspc rule -a Yad state=floating

####            STARTUP ENDING          ####
killall xfce-polkit
command -v /usr/lib/xfce-polkit/xfce-polkit >/dev/null 2>&1
return_val=$?
if [ $return_val -ne 0 ]; then
    echo >&2 "Can't seem to find the /usr/lib/xfce-polkit/xfce-polkit executable"
else
    /usr/lib/xfce-polkit/xfce-polkit &
    return_val=$?
    if [ $return_val -ne 0 ]; then
        echo >&2 "Couldn't fire up xfce-polkit: $return_val"
    fi
fi

killall polybar
command -v polybar >/dev/null 2>&1
if [ $? -ne 0 ]; then
    echo >&2 "Can't seem to find the polybar executable. Starting barless!"
    bspc config top_padding 0
else
    $HOME/.config/polybar/launch
    if [ $? -ne 0 ]; then
        echo >&2 "Couldn't fire up polybar: $?"
    fi
fi

pgrep bspswallow || bspswallow &

killall clipit
clipit &

xsetroot -cursor_name left_ptr &
